"""Added address to company model

Revision ID: e77a4e8dca8e
Revises: 6caeaf373ae3
Create Date: 2025-10-22 13:12:08.581052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77a4e8dca8e'
down_revision: Union[str, Sequence[str], None] = '6caeaf373ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'company', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
